In [1]:
import numpy as np
import cv2

### Define input and kernel

In [16]:
kernel = np.zeros((3,3),dtype=np.uint8)
for i in range(3):
    kernel[0][i] = 1
for i in range(1, 3):
    kernel[i][0] = 1
    
kernel_prime = np.zeros((3,3),dtype=np.uint8)
for i in range(3):
    kernel_prime[2][i] = 1
for i in range(3):
    kernel_prime[i][2] = 1
input = np.ones((8, 8),dtype=np.uint8) * 10
input[0][3] = input[0][6] =  20
for i in range(1, 7):
    input[1][i] = 20
input[2][3] = input[2][5] = input[2][6] = 20
input[3][2] = input[3][5] =  20
input[4][7] = 20
input[5][0] = input[5][5] = input[5][6] = 20
for i in range(5):
    input[6][i] = 20
input[6][6] = 20
input[7][0] = input[7][1] = input[7][3] = 20
input[3][3] = input[3][6] =  30
input[4][2] = input[4][5] =  30
input[5][2] = input[5][4] =  30
input[7][2] = input[7][5] = input[7][7] = 30
print(input)
print(kernel)
print(kernel_prime)

[[10 10 10 20 10 10 20 10]
 [10 20 20 20 20 20 20 10]
 [10 10 10 20 10 20 20 10]
 [10 10 20 30 10 20 30 10]
 [10 10 30 10 10 30 10 20]
 [20 10 30 10 30 20 20 10]
 [20 20 20 20 20 10 20 10]
 [20 20 30 20 10 30 10 30]]
[[1 1 1]
 [1 0 0]
 [1 0 0]]
[[0 0 1]
 [0 0 1]
 [1 1 1]]


### Dilation

In [17]:
dilation = cv2.dilate(input, kernel_prime, borderType=cv2.BORDER_REFLECT)
print(dilation)

[[20 20 20 20 20 20 20 20]
 [20 20 20 20 20 20 20 20]
 [20 20 30 30 30 30 30 30]
 [10 30 30 30 30 30 30 20]
 [20 30 30 30 30 30 20 20]
 [20 30 20 30 30 20 20 20]
 [20 30 30 30 30 30 30 30]
 [20 30 30 30 30 30 30 30]]


### Erosion

In [14]:
erosion = cv2.erode(input, kernel, borderType=cv2.BORDER_REFLECT)
print(erosion)

[[10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10]
 [10 10 10 10 20 10 10 10]
 [10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10]
 [20 20 20 20 10 10 10 10]]
